"""
Configuration file for the Facies Classification pipeline.

This file contains all user-defined parameters, file paths, and settings
that control the pipeline's execution.
"""

import os

# --- 1. DIRECTORY PATHS ---
# Base directory of the project
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Core data folders
DATA_DIR = os.path.join(BASE_DIR, "data")
COMPUTED_DIR = os.path.join(BASE_DIR, "computed")
IMAGE_OUTPUT_DIR = os.path.join(BASE_DIR, "image output")

# Specific data sub-directories
FACIES_DIR_PATH = os.path.join(DATA_DIR, "FaciesTxtFiles")
SEISMIC_DIR_PATH = os.path.join(DATA_DIR, "Seismic")


# --- 2. RAW DATA FILE PATHS ---
# These are the original inputs for the pipeline
WELL_2_PATH = os.path.join(DATA_DIR, "Well2.txt")
MINERAL_FLUID_PATH = os.path.join(DATA_DIR, "Mineral&FluidProperties.txt")

SEISMIC_INTERCEPT_PATH = os.path.join(SEISMIC_DIR_PATH, "SeismicIntercept.txt")
SEISMIC_GRADIENT_PATH = os.path.join(SEISMIC_DIR_PATH, "SeismicGradient.txt")
SEISMIC_INLINE_PATH = os.path.join(SEISMIC_DIR_PATH, "SeismicInlineNumbers.txt")
SEISMIC_XLINE_PATH = os.path.join(SEISMIC_DIR_PATH, "SeismicXlineNumers.txt")


# --- 3. COMPUTED/INTERMEDIATE FILE PATHS ---
# These are the .pkl files generated by the scripts
AVO_DATA_PATH = os.path.join(COMPUTED_DIR, "avo_data.pkl")
IG_DATA_PATH = os.path.join(COMPUTED_DIR, "intercept_gradient_data.pkl")
FACIES_STATS_PATH = os.path.join(COMPUTED_DIR, "facies_statistics.pkl")
MC_SAMPLES_PATH = os.path.join(COMPUTED_DIR, "mc_samples.pkl")


# --- 4. MODEL & SIMULATION PARAMETERS ---

# Number of samples to draw in the Monte Carlo simulation
MC_SAMPLE_COUNT = 100000  # Example value

# Define the facies names.
# This list can be used for ordering, labeling, and plotting.
# (Based on the files in data/FaciesTxtFiles/)
FACIES_NAMES = [
    'FaciesIIa',
    'FaciesIIaOil',
    'FaciesIIb',
    'FaciesIIbOil',
    'FaciesIIc',
    'FaciesIIcOil',
    'FaciesIII',
    'FaciesIV',
    'FaciesV'
]

# --- 5. VISUALIZATION FILENAMES ---
# Define filenames for the output plots
# The full path will be constructed in main.py (e.g., os.path.join(IMAGE_OUTPUT_DIR, PLOT_WELL_LOG))
PLOT_WELL_LOG = "well_log_plot.png"
PLOT_FACIES_PDFS = "facies_pdf_plots.png"
PLOT_FACIES_CDFS = "facies_cdf_plots.png"
PLOT_MOST_LIKELY_MAP = "most_likely_facies_map.png"
PLOT_GROUPED_FACIES_MAP = "grouped_facies_map.png"
PLOT_AVO_CURVES = "avo_reflectivity_curves.png"
PLOT_SEISMIC_DATA = "seismic_data_plots.png"

# You can add more parameters here as needed, such as plot colors,
# colormaps, or specific thresholds.